version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    user: root
    command:
     - --loglevel warning
    volumes:
     - ./redis:/var/lib/redis

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-22
    user: root
    volumes:
     - ./postgresql:/var/lib/postgresql
    environment:
     - DB_USER=postgresql
     - DB_PASS=password
     - DB_NAME=postgresql_poc
     - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.9.6
    user: root
    depends_on:
     - redis
     - postgresql
    ports:
     - "10022:22"
     - "10080:80"
     - "10443:443"
    volumes:
     - ./gitlab:/home/git/data
    environment:
     - DEBUG=false

     - DB_ADAPTER=postgresql
     - DB_HOST=postgresql
     - DB_PORT=5432
     - DB_USER=postgresql
     - DB_PASS=password
     - DB_NAME=postgresql_poc

     - REDIS_HOST=redis
     - REDIS_PORT=6379

     - TZ=America/Bogota
     - GITLAB_TIMEZONE=America/Bogota

     - GITLAB_HTTPS=false
     - SSL_SELF_SIGNED=false

     - GITLAB_HOST=gitlab
     - GITLAB_PORT=10080
     - GITLAB_SSH_PORT=10022
     - GITLAB_RELATIVE_URL_ROOT=
     - GITLAB_SECRETS_DB_KEY_BASE=7CHP7sLpq74RMsFhK7TV7NWxkw77R3nsLJ4dK3nHHsf7pkHgKKrKkxMtxcmtb9Kk

     - GITLAB_ROOT_PASSWORD=pslabc123
     - GITLAB_ROOT_EMAIL=aamadoc@psl.com.co

     - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
     - GITLAB_NOTIFY_PUSHER=false

     - GITLAB_EMAIL=aamadoc@psl.com.co
     - GITLAB_EMAIL_REPLY_TO=aamadoc@psl.com.co
     - GITLAB_INCOMING_EMAIL_ADDRESS=aamadoc@psl.com.co

     - GITLAB_BACKUP_SCHEDULE=daily
     - GITLAB_BACKUP_TIME=01:00

     - SMTP_ENABLED=false
     - SMTP_DOMAIN=www.example.com
     - SMTP_HOST=smtp.gmail.com
     - SMTP_PORT=587
     - SMTP_USER=mailer@example.com
     - SMTP_PASS=password
     - SMTP_STARTTLS=true
     - SMTP_AUTHENTICATION=login

     - IMAP_ENABLED=false
     - IMAP_HOST=imap.gmail.com
     - IMAP_PORT=993
     - IMAP_USER=mailer@example.com
     - IMAP_PASS=password
     - IMAP_SSL=true
     - IMAP_STARTTLS=false

     - OAUTH_ENABLED=false
     - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
     - OAUTH_ALLOW_SSO=
     - OAUTH_BLOCK_AUTO_CREATED_USERS=true
     - OAUTH_AUTO_LINK_LDAP_USER=false
     - OAUTH_AUTO_LINK_SAML_USER=false
     - OAUTH_EXTERNAL_PROVIDERS=

     - OAUTH_CAS3_LABEL=cas3
     - OAUTH_CAS3_SERVER=
     - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
     - OAUTH_CAS3_LOGIN_URL=/cas/login
     - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
     - OAUTH_CAS3_LOGOUT_URL=/cas/logout

     - OAUTH_GOOGLE_API_KEY=
     - OAUTH_GOOGLE_APP_SECRET=
     - OAUTH_GOOGLE_RESTRICT_DOMAIN=

     - OAUTH_FACEBOOK_API_KEY=
     - OAUTH_FACEBOOK_APP_SECRET=

     - OAUTH_TWITTER_API_KEY=
     - OAUTH_TWITTER_APP_SECRET=

     - OAUTH_GITHUB_API_KEY=
     - OAUTH_GITHUB_APP_SECRET=
     - OAUTH_GITHUB_URL=
     - OAUTH_GITHUB_VERIFY_SSL=

     - OAUTH_GITLAB_API_KEY=
     - OAUTH_GITLAB_APP_SECRET=

     - OAUTH_BITBUCKET_API_KEY=
     - OAUTH_BITBUCKET_APP_SECRET=

     - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
     - OAUTH_SAML_IDP_CERT_FINGERPRINT=
     - OAUTH_SAML_IDP_SSO_TARGET_URL=
     - OAUTH_SAML_ISSUER=
     - OAUTH_SAML_LABEL="Our SAML Provider"
     - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
     - OAUTH_SAML_GROUPS_ATTRIBUTE=
     - OAUTH_SAML_EXTERNAL_GROUPS=
     - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
     - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
     - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
     - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

     - OAUTH_CROWD_SERVER_URL=
     - OAUTH_CROWD_APP_NAME=
     - OAUTH_CROWD_APP_PASSWORD=

     - OAUTH_AUTH0_CLIENT_ID=
     - OAUTH_AUTH0_CLIENT_SECRET=
     - OAUTH_AUTH0_DOMAIN=

     - OAUTH_AZURE_API_KEY=
     - OAUTH_AZURE_API_SECRET=
     - OAUTH_AZURE_TENANT_ID=

  postgresqlsonar:
    restart: always
    image: sameersbn/postgresql:9.4-22
    user: root
    volumes:
     - ./postgresql-sonar:/var/lib/postgresql
    ports:
     - "5432:5432"
    environment:
     - DB_USER=postgresql
     - DB_PASS=password
     - DB_NAME=postgresql_poc
     - DB_EXTENSION=pg_trgm

  sonarqube:
    restart: always
    image: sonarqube:lts-alpine
    user: root
    depends_on:
     - postgresqlsonar
    links:
     - gitlab
    volumes:
     - ./sonarqube/data:/opt/sonarqube/data
     - ./sonarqube/extensions:/opt/sonarqube/extensions
    ports:
     - "9000:9000"
     - "9092:9092"
    environment:
     - SONARQUBE_JDBC_USERNAME=postgresql
     - SONARQUBE_JDBC_PASSWORD=password
     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresqlsonar/postgresql_poc

  jenkins:
    restart: always
    image: jenkins:alpine
    user: root
    volumes:
     - ./jenkins:/var/jenkins_home
    links:
     - gitlab
     - sonarqube
    ports:
     - "8080:8080"
     - "50000:50000"

  nginx:
    restart: always
    image: nginx:stable-alpine
    user: root
    depends_on:
     - jenkins
     - gitlab
     - sonarqube
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/ssl:/etc/nginx/ssl
    ports:
     - "80:80"
     - "443:443"
